export const holidayDefinitions = [
    {
        id: "christmas",
        name: "Christmas",
        month: 12,
        day: 25,
        icon: "🎄",
        moments: [
            {
                daysBefore: 45,
                priority: 70,
                score: 90,
                title: "Christmas is about six weeks away",
                description: "Now is a great time to begin planning gifts.",
                actionLabel: "Create Gift Checklist",
                template: "christmas_gifts",
            },
            {
                daysBefore: 28,
                priority: 70,
                score: 85,
                title: "Ready to start Christmas shopping?",
                description: "Shopping early helps avoid holiday stress.",
                actionLabel: "Create Shopping Checklist",
                template: "christmas_shopping",
            },
            {
                daysBefore: 14,
                priority: 70,
                score: 88,
                title: "Christmas dinner is coming up",
                description: "Let's plan your holiday meal.",
                actionLabel: "Create Meal Checklist",
                template: "christmas_meal",
            },
            {
                daysBefore: 3,
                priority: 70,
                score: 99,
                title: "Christmas is almost here",
                description: "A few final preparations can make tomorrow easier.",
                actionLabel: "Create Final Checklist",
                template: "christmas_final",
            },
        ],
    },

    {
        id: "independence-day",
        name: "Independence Day",
        month: 7,
        day: 4,
        icon: "🇺🇸",
        moments: [
            {
                daysBefore: 14,
                priority: 65,
                score: 80,
                title: "July 4th is coming up",
                description: "Evergrove can help you prepare food, drinks, and outdoor plans.",
                actionLabel: "Create July 4th Checklist",
                template: "independence_day_prep",
            },
            {
                daysBefore: 3,
                priority: 65,
                score: 95,
                title: "July 4th is almost here",
                description: "A quick final checklist can help the day go smoother.",
                actionLabel: "Create Final Checklist",
                template: "independence_day_final",
            },
        ],
    },
]