export const holidayDefinitions = [
    {
        id: "christmas",
        name: "Christmas",
        month: 12,
        day: 25,
        icon: "🎄",
        moments: [
            {
                daysBefore: 45,
                priority: 70,
                score: 90,
                title: "Christmas is about six weeks away",
                description: "Now is a great time to begin planning gifts.",
                actionLabel: "Create Gift Checklist",
                template: "christmas_gifts",
            },
            {
                daysBefore: 28,
                priority: 70,
                score: 85,
                title: "Ready to start Christmas shopping?",
                description: "Shopping early helps avoid holiday stress.",
                actionLabel: "Create Shopping Checklist",
                template: "christmas_shopping",
            },
            {
                daysBefore: 14,
                priority: 70,
                score: 88,
                title: "Christmas dinner is coming up",
                description: "Let's plan your holiday meal.",
                actionLabel: "Create Meal Checklist",
                template: "christmas_meal",
            },
            {
                daysBefore: 3,
                priority: 70,
                score: 99,
                title: "Christmas is almost here",
                description: "A few final preparations can make tomorrow easier.",
                actionLabel: "Create Final Checklist",
                template: "christmas_final",
            },
        ],
    },

    {
        id: "independence-day",
        name: "Independence Day",
        month: 7,
        day: 4,
        icon: "🇺🇸",
        moments: [
            {
                daysBefore: 14,
                priority: 65,
                score: 80,
                title: "July 4th is coming up",
                description: "Evergrove can help you prepare food, drinks, and outdoor plans.",
                actionLabel: "Create July 4th Checklist",
                template: "independence_day_prep",
            },
            {
                daysBefore: 3,
                priority: 65,
                score: 95,
                title: "July 4th is almost here",
                description: "A quick final checklist can help the day go smoother.",
                actionLabel: "Create Final Checklist",
                template: "independence_day_final",
            },
        ],
    },

    {
        id: "halloween",
        name: "Halloween",
        month: 10,
        day: 31,
        icon: "🎃",
        moments: [
            {
                daysBefore: 30,
                priority: 60,
                score: 82,
                title: "Halloween is coming up",
                description: "Now is a good time to plan costumes, candy, and decorations.",
                actionLabel: "Create Halloween Checklist",
                template: "halloween_prep",
            },
            {
                daysBefore: 3,
                priority: 60,
                score: 96,
                title: "Halloween is almost here",
                description: "A quick final checklist can help the night go smoothly.",
                actionLabel: "Create Final Checklist",
                template: "halloween_final",
            },
        ],
    },

    {
        id: "thanksgiving",
        name: "Thanksgiving",
        type: "nth-weekday",
        month: 11,
        weekday: 4, // Thursday
        occurrence: 4,
        icon: "🦃",
        moments: [
            {
                daysBefore: 30,
                priority: 68,
                score: 84,
                title: "Thanksgiving is coming up",
                description: "Now is a good time to plan the menu, guests, and grocery list.",
                actionLabel: "Create Thanksgiving Checklist",
                template: "thanksgiving_prep",
            },
            {
                daysBefore: 10,
                priority: 68,
                score: 90,
                title: "Thanksgiving shopping is coming up",
                description: "A shopping checklist can help avoid last-minute grocery runs.",
                actionLabel: "Create Shopping Checklist",
                template: "thanksgiving_shopping",
            },
            {
                daysBefore: 3,
                priority: 68,
                score: 98,
                title: "Thanksgiving is almost here",
                description: "A final prep checklist can help the day feel calmer.",
                actionLabel: "Create Final Checklist",
                template: "thanksgiving_final",
            },
        ],
    },
]